* Profesor: Alvaro Javier Cangrejo

# Pandas Groupby

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
realtor_data = pd.read_csv("realtor-data.csv", parse_dates=["prev_sold_date"]) ## Base de agentes inmobiliarios
restaurants = pd.read_csv("/content/california_restaurants.csv")

In [ ]:
realtor_data.sample(2)

,status,bed,bath,acre_lot,city,state,zip_code,house_size,prev_sold_date,price
858874,for_sale,5.0,5.0,0.03,New York City,New York,11233.0,3290.0,NaT,3330000.0
19125,for_sale,6.0,4.0,0.25,Bayamon,Puerto Rico,961.0,2705.0,NaT,127600.0

* ¿Que ciudades tienen las casas más caras y más baratas en EEUU?
* ¿Que combinacione de dormitorio y baño son las más comunes ?

In [ ]:
## Agrupemos los datos, esto nos indica que es una data frame agrupado
grp = realtor_data.groupby("city")
grp

In [ ]:
## Para conocer los grupos debemos iterar a través de los grupo y observar la respuesta real
for city, data in grp:
  print(city)
  print(data.shape[0])

Abbot
15
Aberdeen
201
Abington
179
Absecon
353
Absecon Highlands
4
Accord
5
Acton
851
Acushnet
97
Acworth
131
Adams
870
Adamstown Township
7
Addisleigh Park
27
Addison
125
Adelphia
3
Adjuntas
33
Agawam
872
Aguada
261
Aguadilla
188
Aguas Buenas
82
Aibonito
102
Airmont
30
Albany
71
Albertson
5
Albion
4
Alburgh
75
Aldan
43
Alexander
28
Alexandria
109
Alexandria Township
27
Alford
77
Alfred
13
Allagash
1
Allamuchy Township
160
Allendale
128
Allenhurst
22
Allenstown
96
Allentown
184
Allenwood
21
Alloway
66
Allston
30
Alna
1
Alpha
19
Alpine
199
Alstead
235
Alton
551
Amawalk
2
Ambler
5
Amenia
73
Amesbury
484
Amherst
1112
Amity
10
Anasco
53
Ancram
56
Ancramdale
6
Andover
1217
Annandale
2
Anson
80
Ansonia
233
Antrim
228
Appleton
120
Aquinnah
7
Arden
6
Ardmore
56
Ardsley
35
Arecibo
481
Argyle
103
Argyle Township
9
Arlington
1234
Armonk
34
Arrowsic
1
Arroyo
57
Arundel
53
Arverne
63
Asbury Park
432
Ashburnham
201
Ashby
152
Ashfield
64
Ashford
187
Ashland
373
Aston
72
Astoria
1006
Atco
294
Athens
32
Athol
465
Atkinson
287
Atlantic City
1400
Atlantic Highlands
115
Atlantique
2
Attleboro
593
Auburn
940
Audubon
73
Augusta
607
Ausable
5
Austerlitz
184
Avalon
310
Avalon Manor
22
Avenel
285
Averill
7
Avon
1329
Avon By The Sea
41
Avondale
8
Ayer
288
Back Bay
86
Baileyville
24
Bakersfield
14
Bala Cynwyd
27
Baldwin
33
Baltimore
44
Bangor
675
Bar Harbor
183
Barceloneta
65
Bardonia
22
Baring Plt
6
Barkhamsted
274
Barnard
150
Barnegat
492
Barnegat Light
14
Barnegat Township
14
Barnet
205
Barnstable
403
Barnstead
322
Barranquitas
47
Barre
1497
Barrington
913
Barryville
7
Bartlett
340
Barton
258
Basking Ridge
16
Bass River
5
Bath
481
Bath Beach
10
Bay Head
36
Bayamon
1927
Bayamón
67
Bayonne
1003
Bayside
1933
Bayville
335
Beach Haven
74
Beach Haven West
31
Beachwood
133
Beacon Falls
97
Beals
28
Bear
64
Beaver Cove
6
Becket
985
Bed Stuy
241
Beddington
8
Bedford
838
Bedminster Twp
360
Bedstuy Brooklyn
34
Beechhurst
189
Beekmantown
3
Beesleys Point
18
Belchertown
1441
Belfast
144
Belford
59
Belgrade
148
Belle Harbor
12
Belle Mead
91
Belle Terre
5
Belleplain
10
Bellerose
311
Bellerose village
10
Belleville
1500
Bellingham
198
Bellmawr
91
Belmar
130
Belmont
979
Belvidere
106
Benedicta
11
Bennington
494
Bensalem
74
Benson
64
Benton
64
Bergenfield
442
Berkeley
50
Berkeley Heights
8
Berkeley Heights Twp
352
Berkeley Township
2
Berkley
126
Berkshire
67
Berlin
1562
Bernards Twp
1053
Bernardston
316
Bernardsville
469
Berwick
89
Berwyn
36
Bethany
99
Bethel
442
Bethlehem
279
Bethlehem Township
24
Beverly
370
Biddeford
237
Big Lake Township
1
Big Moose Township
1
Billerica
653
Bingham
36
Black Brook
1
Blackstone
180
Blackwood
339
Blaine
16
Blairstown
113
Blanchard Township
8
Blandford
216
Blauvelt
12
Block Island
45
Bloomfield
2677
Blooming Grove
6
Bloomingdale
166
Bloomsbury
10
Blue Anchor
3
Blue Hill
138
Bogota
297
Bolton
499
Boonton
194
Boonton Township
187
Boothbay
196
Boothbay Harbor
132
Boothwyn
40
Boqueron
1
Bordentown
299
Boscawen
71
Boston
31502
Bound Brook
372
Bourne
321
Bournedale
10
Bow
79
Bowdoin
14
Bowdoinham
80
Bowerbank
12
Boxborough
694
Boxford
164
Boylston
198
Bozrah
99
Bradford
360
Bradley
28
Bradley Beach
82
Braintree
375
Branchburg
33
Branchburg Township
356
Branchville
25
Brandon
310
Branford
505
Brattleboro
785
Breezy Point
8
Bremen
2
Brentwood
455
Brewer
199
Brewster
302
Briarcliff Manor
22
Briarwood
509
Brick
1706
Brick Township
15
Bridgeport
1244
Bridgeton
1028
Bridgewater
646
Bridgewater Twp
922
Bridgton
218
Bridport
43
Brielle
123
Brigantine
381
Brigantine City
3
Brighton
254
Brighton Beach
1
Brimfield
215
Bristol
3217
Broad Channel
78
Brockton
1189
Bronx
10101
Bronxville
446
Brookfield
499
Brookhaven
102
Brooklawn
36
Brooklin
105
Brookline
2685
Brooklyn
22690
Brooklyn Heights
4
Brooks
31
Brooksville
81
Brookton
6
Brookville
1
Broomall
80
Brownfield
47
Brownington
76
Browns Mills
852
Brownville
232
Brunswick
412
Bryn Mawr
77
Buckfield
20
Buckland
205
Bucksport
176
Budd Lake
5
Buena
91
Buena Vista
2
Buena Vista Township
36
Burke
303
Burleigh
4
Burlington
2109
Burlington City
4
Burlington Township
36
Burnham
4
Burrillville
489
Bushkill
342
Butler
165
Buxton
73
Buzzards Bay
110
Byram Township
285
Byron
1
Cabo Rojo
380
Cabot
148
Cadyville
1
Caguas
759
Calais
192
Caldwell
76
Caldwell Boro Township
154
Califon
60
Cambria Heights
165
Cambridge
3341
Cambridge Village
6
Camden
416
Campton
523
Camuy
143
Canaan
854
Canarsie
32
Candia
15
Canovanas
288
Canterbury
481
Canton
1245
Cape Charles
11
Cape Elizabeth
64
Cape May
184
Cape May Beach
19
Cape May Court House
645
Cape May Point
22
Caratunk
6
Caribou
306
Carlisle
69
Carlstadt
118
Carmel
44
Carmel Hamlet
1
Carneys Point
86
Caroga
3
Carolina
1421
Carrabassett Valley
96
Carroll
67
Carroll Plt
3
Carrying Place Town Township
3
Carteret
495
Carthage
20
Carver
148
Carversville
1
Cary Plt
6
Casco
438
Castine
80
Castle Hill
29
Castleton
616
Caswell
9
Catano
162
Cataumet
38
Cathance Township
14
Cavendish
361
Cayey
340
Cedar Grove
308
Cedarhurst
6
Cedarville
111
Ceiba
37
Centereach
55
Centerville
336
Central Falls
178
Central Valley
3
Chadds Ford
50
Champlain
32
Chaplin
139
Chapman
28
Chappaqua
3
Charlemont
81
Charleston
109
Charlestown
751
Charlotte
64
Charlton
378
Chatham
770
Chatham Township
430
Chatham Village
3
Chatsworth
14
Chazy
11
Chebeague Island
4
Chelmsford
646
Chelsea
804
Cheltenham
26
Cherry Hill
380
Cherry Hill Township
2
Cherryfield
52
Cheshire
900
Chesilhurst
17
Chester
1395
Chester Heights
1
Chester Township
332
Chester Twp
30
Chesterfield
817
Chesterville
38
Chestnut Ridge
15
Cheyney
2
Chichester
80
Chicopee
1292
Chilmark
15
China
248
Chincoteague
20
Chittenden
31
Christiansted
1287
Ciales
125
Cidra
346
Cinnaminson
120
City of Orange Township
773
Claremont
671
Clarendon
220
Clark
233
Clarksboro
60
Clarksburg
265
Clarksville
14
Claverack
79
Claymont
94
Clayton
204
Clementon
146
Clermont
26
Cliffside Park
1294
Cliffwood
35
Cliffwood Beach
25
Clifton
2711
Clifton Heights
90
Clinton
434
Clinton Corners
37
Clinton Township
163
Clintonville
8
Closter
186
Coamo
103
Cody
3
Cohasset
173
Colchester
626
Cold Spring
6
Colebrook
248
College Point
752
Collingdale
33
Collingswood
68
Colonia
276
Colrain
105
Colts Neck
232
Columbia
407
Columbia Falls
36
Columbus
302
Comerio
85
Concord
1231
Concord Township
12
Condado
1
Congers
18
Connor Township
1
Conshohocken
53
Conway
953
Cookstown
33
Cooper
2
Copake
169
Copake Falls
17
Coplin Plt
7
Coram
80
Corbin City
24
Corinna
20
Corinth
139
Cornish
152
Cornville
65
Cornwall
149
Corona
1087
Corozal
194
Cortlandt Manor
1
Cos Cob
35
Cotuit
116
Coventry
1737
Craftsbury
137
Cranberry Isles
58
Cranbury
168
Cranford
419
Cranston
1833
Craryville
30
Crawford
8
Cream Ridge
153
Cresskill
404
Cromwell
662
Cross Lake Township
10
Crosswicks
12
Croton On Hudson
9
Crown Heights
297
Crown Point
140
Croydon
124
Crum Lynne
23
Crystal
8
Cuddebackville
1
Culebra
13
Cumberland
1587
Cummaquid
14
Cummington
67
Cushing
126
Cutler
26
Dallas Plt
69
Dalton
321
Damariscotta
59
Danbury
549
Danby
278
Danforth
29
Danvers
285
Danville
408
Darby
170
Darien
159
Dartmouth
306
Dayton
68
Deal
33
Dedham
654
Deep River
177
Deepwater
21
Deer Isle
143
Deerfield
389
Deering
49
Del Haven
49
Delanco
87
Delaware
57
Delaware City
35
Delaware Township
2
Delaware Water Gap
4
Delmont
25
Delran
148
Demarest
193
Denmark
29
Dennis
292
Dennis Port
169
Dennis Township
9
Dennisville
18
Dennysville
15
Denville
615
Deptford
76
Deptford Township
6
Derby
594
Derry
502
Detroit
25
Devens
172
Devon
7
Devonshire
30
Dexter
219
Diamond Beach
3
Dighton
126
Dingmans Ferry
237
Dixfield
156
Dixmont
37
Dobbs Ferry
62
Dorado
838
Dorchester
161
Dorothy
41
Dorset
347
Douglas
298
Douglaston
311
Dover
2451
Dover Foxcroft
100
Dover Plains
74
Doylestown
7
Dracut
512
Dresden
99
Dresher
10
Drexel Hill
221
Dublin
54
Dudley
375
Dummer
30
Dummerston
26
Dumont
321
Dunbarton
92
Dunellen
318
Dunellen Borough
21
Dunstable
75
Durham
463
Duxbury
154
Dyer Brook
8
Dyker Heights
7
Eagle Lake
47
Eagleswood Township
11
Eagleville
2
East Amwell
13
East Amwell Township
74
East Bangor
3
East Boston
128
East Bridgewater
151
East Brookfield
21
East Brunswick
1191
East Chatham
35
East Dennis
126
East Elmhurst
1130
East Falmouth
633
East Flatbush
125
East Granby
356
East Greenbush
1
East Greenwich
519
East Greenwich Township
7
East Haddam
582
East Hampton
588
East Hanover
213
East Hartford
1621
East Harwich
7
East Haven
409
East Hills
3
East Kingston
18
East Longmeadow
373
East Lyme
679
East Machias
61
East Marion
8
East Millinocket
27
East Montpelier
73
East Moxie Township
9
East Nassau
27
East New York
3
East Newark
48
East Orange
2605
East Providence
822
East Rutherford
304
East Sandwich
174
East Setauket
19
East Stroudsburg
172
East Vineland
5
East Wareham
33
East Windsor
1241
Eastampton
95
Eastbrook
15
Eastchester
46
Eastford
162
Eastham
302
Easthampton
580
Easton
570
Eastport
97
Eaton
32
Eatontown
198
Ebeemee Township
6
Eddington
56
Eddystone
6
Eden
260
Edgartown
72
Edgecomb
154
Edgewater
1439
Edgewater Park
65
Edinburg
1
Edison
1576
Edmunds Township
6
Effingham
117
Egg Harbor
9
Egg Harbor City
370
Egg Harbor Township
1674
Egremont
135
Elberon
40
Eldora
28
Eldred
15
Eliot
158
Elizabeth
234
Elizabeth City
1346
Elizabethtown
15
Elizaville
6
Elk Township
4
Elkins Park
113
Ellington
747
Elliottsville Township
2
Ellsworth
131
Elmer
347
Elmhurst
969
Elmont
170
Elmore
147
Elmsford
33
Elmwood Park
689
Elsmere
2
Embden
64
Emerson
117
Enfield
2191
Englewood
792
Englewood Cliffs
277
Englishtown
112
Enosburg Falls
131
Epping
634
Epsom
197
Erdenheim
3
Erial
2
Erma
46
Errol
14
Erving
107
Erwinna
1
Essex
470
Essex Fells
42
Essington
56
Estell Manor
151
Etna
105
Eustis
26
Everett
709
Evesham
4
Ewing
470
Ewing Township
26
Exeter
969
Fair Haven
330
Fair Lawn
554
Fairfax
100
Fairfield
874
Fairfield Twp
7
Fairhaven
251
Fairlee
59
Fairless Hills
30
Fairton
5
Fairview
307
Fajardo
176
Fall River
793
Falmouth
569
Fanwood
122
Far Hills
78
Far Rockaway
105
Farmingdale
417
Farmington
1502
Farmingville
7
Fayette
66
Fayston
175
Feasterville Trevose
24
Fenway
56
Ferrisburgh
120
Fieldsboro
4
Fishkill
2
Fitchburg
1078
Fitzwilliam
230
Flagstaff Township
1
Flatbush
43
Flatlands
1
Flemington
202
Fletcher
98
Fletchers Landing Township
1
Floral Park
424
Florence
119
Florham Park
292
Florida
191
Flourtown
9
Flushing
4514
Folcroft
51
Folsom
78
Fords
267
Forest City Township
7
Forest Hills
3206
Forestdale
45
Forked River
364
Fort Ann
98
Fort Fairfield
102
Fort Kent
136
Fort Lee
3304
Fort Washington
13
Fortescue
31
Foster
133
Foxboro
274
Framingham
1053
Framington
22
Francestown
17
Franconia
171
Frankford Township
100
Frankfort
81
Franklin
1209
Franklin Lakes
391
Franklin Park
26
Franklin Township
6
Franklin Twp
1026
Franklinville
442
Frederiksted
426
Fredon
8
Fredon Township
135
Freedom
204
Freehold
886
Freeman Township
1
Freeport
182
Freetown
141
Frelinghuysen
97
Fremont
81
Frenchboro
13
Frenchtown
11
Frenchville
3
Fresh Meadows
621
Friendship
3
Frye Island
14
Fryeburg
128
Furlong
1
Gallatin
16
Galloway
43
Galloway Township
775
Garden City Park
1
Gardiner
255
Gardner
369
Garfield
642
Garland
129
Garnerville
25
Garnet Valley
46
Garwood
73
Georgetown
220
Georgia
104
Ghent
42
Gibbsboro
27
Gibbstown
169
Gilead
1
Gilford
394
Gill
74
Gilmanton
178
Gilsum
198
Gladwyne
27
Glassboro
435
Glastonbury
997
Glen Cove
15
Glen Gardner
36
Glen Head
6
Glen Mills
70
Glen Oaks
46
Glen Riddle
2
Glen Ridge
130
Glen Ridge Boro Township
314
Glen Rock
295
Glen Spey
25
Glenburn
51
Glendale
973
Glendora
58
Glenolden
120
Glenside
44
Glenwood
2
Glenwood Landing
2
Glenwood Plt
1
Glocester
272
Gloucester
167
Gloucester City
93
Gloucester Township
7
Glover
171
Goffstown
146
Gorham
314
Goshen
683
Gouldsboro
55
Gowanus
3
Grafton
705
Granby
1138
Grand Falls Township
2
Grand Isle
142
Grand Lake Stream
16
Grand Lake Stream Plt
7
Grantham
657
Granville
315
Granville Village
64
Grassy Sound
2
Gray
136
Great Barrington
764
Great Neck
352
Great Pond
14
Greeley
9
Green Brook
243
Green Creek
24
Green Township
157
Greenbush
31
Greene
128
Greenfield
898
Greenfield Township
9
Greenlaw Chopping Twp
5
Greenport
28
Greensboro
94
Greenvale
1
Greenville
168
Greenwich
431
Greenwich Township
32
Greenwood
3
Greenwood Lake
65
Grenloch
2
Grindstone Twp
2
Griswold
739
Groton
1209
Groveland
54
Guanica
61
Guayama
190
Guayanilla
24
Guaynabo
1885
Guildhall
20
Guilford
709
Gulph Mills
1
Gurabo
230
Guttenberg
1119
Hackensack
1107
Hackettstown
114
Haddam
318
Haddon Heights
72
Haddon Township
36
Haddonfield
140
Hadley
365
Hague
51
Hainesport
132
Haledon
232
Hales Location
14
Halifax
316
Hallowell
340
Hamburg
142
Hamden
1065
Hamilton
1811
Hamilton Square
12
Hamilton Township
360
Hamlin
7
Hammonton
516
Hampden
361
Hampstead
198
Hampton
1119
Hampton Falls
12
Hancock
386
Hancocks Bridge
7
Hanover
433
Hanover Township
10
Hanover Twp
292
Hanson
169
Harding Township
362
Hardwick
537
Hardwick Twp
34
Hardyston
233
Harmony
21
Harmony Township
17
Harpswell
103
Harriman
4
Harrington
44
Harrington Park
75
Harrison
412
Harrisville
18
Hartford
4496
Hartland
286
Hartsdale
150
Harvard
204
Harvey Cedars
25
Harwich
232
Harwich Port
107
Harwinton
228
Hasbrouck Heights
231
Hastings On Hudson
48
Hatfield
134
Hatillo
275
Hato Rey
1
Haverford
28
Haverhill
1896
Haverstraw
30
Havertown
175
Hawley
38
Haworth
56
Hawthorne
397
Haynesville
20
Hazlet
285
Hazlet Township
3
Hebron
420
Heislerville
36
Helmetta
80
Hempstead
1
Henniker
213
Hermon
69
Hersey
3
Herseytown Township
1
High Bridge
106
Highgate
110
Highland Lake
7
Highland Mills
20
Highland Park
394
Highlands
107
Hightstown
235
Hill
44
Hillburn
6
Hillcrest
44
Hillsborough
1110
Hillsborough Twp
959
Hillsdale
277
Hillside
583
Hinesburg
82
Hingham
295
Hinsdale
1053
Hiram
17
Ho Ho Kus
100
Hoboken
3001
Hockessin
20
Hodgdon
23
Holbrook
109
Holden
367
Holderness
82
Holland
233
Holland Township
20
Hollis
496
Hollis Center
26
Hollis Hills
63
Holliston
177
Holmdel
272
Holmes
23
Holyoke
831
Hooksett
379
Hoosick
79
Hoosick Falls
183
Hopatcong
987
Hope
67
Hopedale
74
Hopelawn
49
Hopewell
119
Hopewell Junction
24
Hopewell Township
56
Hopkinton
864
Hormigueros
86
Houlton
94
Howard Beach
999
Howell
1074
Howland
41
Hubbardston
173
Hubbardton
58
Hudson
1436
Hudson Falls
11
Huguenot
10
Hull
414
Hulmeville
1
Humacao
253
Huntingdon Valley
10
Huntington
218
Hyannis
404
Hyannis Port
48
Hyde Park
240
Independence Township
158
Industry
19
Interlaken
4
Inwood
1
Ipswich
249
Irasburg
39
Irvington
1978
Isabela
135
Iselin
342
Isla Verde
1
Island Falls
22
Island Heights
48
Isle Au Haut
23
Isle La Motte
30
Islesboro
86
Jackman
4
Jackson
1823
Jackson Heights
1481
Jaffrey
358
Jamaica
3758
Jamaica Estates
22
Jamaica Plain
87
Jamesburg
145
Jamestown
93
Jay
217
Jayuya
18
Jefferson
157
Jefferson City
20
Jefferson Township
641
Jenkintown
46
Jericho
113
Jersey City
10190
Jobstown
48
Johnson
178
Johnsonville
7
Johnston
892
Jonesboro
20
Jonesport
63
Juana Diaz
167
Juliustown
22
Juncos
188
Kauneonga Lake
3
Keansburg
224
Kearny
873
Keasbey
41
Keene
1118
Keeseville
76
Kendall Park
47
Kenduskeag
46
Kenilworth
193
Kennebunk
81
Kennebunkport
74
Kennett Square
63
Kensington
131
Kent
106
Kew Garden Hills
26
Kew Gardens
624
Kew Gardens Hills
420
Keyport
202
Killingly
820
Killington
2264
Killingworth
180
Kinderhook
27
Kineo Township
2
Kingfield
35
Kingman Township
18
Kingsbury
10
Kingsbury Plt
8
Kingshill
168
Kingston
528
Kingwood
2
Kingwood Township
36
Kinnelon
378
Kirby
65
Kittery
159
Knowlton
25
Knox
1
Lacey
10
Lacey Township
2
Lackawaxen
4
Laconia
948
Lafayette
67
Lafayette Hill
12
Lagrange
26
Lagrangeville
12
Lajas
77
Lake Como
18
Lake Grove
8
Lake Success
4
Lake View Plt
22
Lakehurst
19
Lakeville
173
Lakewood
1240
Lambertville
194
Lamoine
36
Lancaster
370
Landenberg
7
Landgrove
41
Landing
9
Landisville
143
Lanesborough
287
Langdon
43
Langhorne
52
Lanoka Harbor
55
Lansdowne
149
Larchmont
130
Lares
168
Las Marias
34
Las Piedras
92
Laurel Springs
24
Laureldale
13
Laurelton
162
Laurence Harbor
28
Lavallette
241
Lawnside
19
Lawrence
535
Lawrence Township
120
Lawrenceville
165
Lebanon
1220
Ledgewood
12
Ledyard
817
Lee
339
Leeds
2
Leesburg
60
Lehman
11
Leicester
559
Lemington
6
Lempster
35
Lenox
446
Leominster
644
Leonardo
57
Leonia
168
Levant
49
Leverett
94
Levittown
212
Lewes
1
Lewis
15
Lewiston
559
Lexington
689
Lexington Township
4
Leyden
37
Liberty
63
Liberty Corner
9
Liberty Township
62
Limerick
44
Limestone
30
Limington
149
Lincoln
1816
Lincoln Park
467
Lincoln Plt
1
Lincolnton
2
Lincolnville
100
Lincroft
136
Linden
679
Lindenwold
114
Lindenwood Howard Beach
24
Linneus
30
Linwood
260
Lisbon
412
Litchfield
659
Little Compton
55
Little Egg Harbor
458
Little Egg Harbor Township
246
Little Falls
468
Little Ferry
509
Little Neck
247
Little Silver
146
Littleton
407
Livermore
49
Livermore Falls
172
Livingston
735
Loch Arbour Village
12
Locust
8
Lodi
546
Loiza
164
Londonderry
714
Long Beach Township
278
Long Branch
601
Long Hill Township
324
Long Island City
718
Long Valley
6
Longmeadow
257
Longport
53
Lopatcong
61
Lords Valley
58
Loudon
117
Lovell
31
Lowell
1404
Lower Mt Bethel Township
3
Lower Township
56
Lubec
104
Ludlow
3467
Lumberton
252
Lumberton Township
9
Lumberville
1
Lunenburg
489
Luquillo
54
Lyman
85
Lyme
240
Lyndeborough
103
Lyndhurst
447
Lyndon
570
Lynn
999
Lynnfield
77
Machias
87
Machiasport
47
Macwahoc Plt
1
Madawaska
113
Madawaska Lake Township
1
Madbury
48
Madison
1235
Madrid Twp
9
Magnolia
43
Mahopac
1
Mahwah
271
Maine
5
Malaga
35
Malba
71
Malden
967
Malden On Hudson
1
Malvern
23
Mamaroneck
110
Manahawkin
589
Manalapan
641
Manasquan
286
Manati
195
Manatí
15
Manchester
4436
Manchester Township
146
Manhasset
21
Manhattan
6381
Manorhaven
5
Manorville
1
Mansfield
1083
Mantoloking
154
Mantua
174
Manville
417
Maple Glen
1
Maple Shade
140
Mapleton
50
Maplewood
710
Marblehead
206
Marcus Hook
74
Margate
418
Margate City
27
Mariaville
5
Maricao
49
Marion
128
Marion Township
9
Marlboro
477
Marlboro Township
3
Marlborough
986
Marlow
125
Marlton
408
Marmora
186
Mars Hill
37
Marshfield
268
Marstons Mills
208
Masardis
4
Mashpee
1052
Mason
92
Maspeth
632
Matamoras
78
Matawan
299
Matinicus Isle Plt
1
Mattapoisett
308
Mattawamkeag
12
Mattituck
1
Maunabo
28
Mauricetown
16
Maxfield
3
Mayaguez
483
Maynard
280
Mays Landing
1551
Maywood
225
McCormick
25
Mechanic Falls
33
Meddybemps
5
Medfield
146
Medford
2122
Medford Lakes
25
Media
161
Medway
184
Melrose
589
Mendham
270
Mendham Township
348
Mendon
266
Menlo Park Terrace
61
Mercer
2
Mercerville
11
Merchantville
27
Meredith
661
Meriden
1510
Merion Station
16
Merrill
19
Merrimac
103
Merrimack
224
Methuen
1072
Metuchen
379
Mexico
97
Mickleton
77
Middle Island
22
Middle Smithfield Township
9
Middle Township
9
Middle Village
527
Middleboro
373
Middlebury
582
Middlefield
181
Middlesex
702
Middleton
381
Middletown
1873
Middletown Springs
64
Middletown Township
6
Midland Park
76
Midtown
229
Milan
49
Milbridge
84
Milford
1445
Millbrook
40
Millburn
717
Millbury
266
Miller Place
40
Millerton
139
Millinocket
117
Millis
638
Millsfield
4
Millstone
114
Millstone Township
6
Milltown
259
Millville
2347
Milmay
47
Milmont Park
4
Milo
51
Milroy
3
Milton
1195
Milton Township
11
Mine Hill
177
Mineville
19
Minot
14
Minotola
39
Misery Township
1
Mizpah
20
Moca
96
Molunkus Township
2
Mongaup Valley
1
Monhegan Island Plt
1
Monkton
58
Monmouth
236
Monmouth Beach
137
Monmouth Junction
96
Monroe
2290
Monroe Township
164
Monroeville
148
Monsey
59
Monson
418
Mont Vernon
144
Montague
368
Montauk
79
Montclair
2036
Montebello
4
Monterey
231
Montgomery
248
Montgomery Twp
329
Monticello
37
Montpelier
319
Montrose
1
Montvale
143
Montville
707
Montville Township
683
Monument Beach
10
Moonachie
48
Moorestown
284
Moosehead Junction Township
5
Moretown
74
Morgan
49
Morganville
348
Moriah
131
Moriah Center
2
Morovis
137
Morrill
30
Morris
152
Morris Plains
195
Morris Plains Boroug
12
Morris Township
7
Morris Twp
683
Morrisonville
38
Morristown
1296
Morrisville
70
Morton
32
Moscow
77
Moultonborough
352
Mount Arlington
138
Mount Bethel
13
Mount Chase
24
Mount Desert
224
Mount Ephraim
47
Mount Holly
769
Mount Laurel
620
Mount Olive Township
441
Mount Royal
52
Mount Sinai
45

In [ ]:
## Ahora, para volver más claro el ejericico agrupemos ciudad con estado

realtor_data["city_state"] = realtor_data["city"] + "," + realtor_data["state"]
grp = realtor_data.groupby("city_state", as_index= False) ## as_index = False indica que la variable agrupacion ciudad-estado no la asigne como indice

In [ ]:
realtor_data.sample(3)

,status,bed,bath,acre_lot,city,state,zip_code,house_size,prev_sold_date,price,city_state
228507,for_sale,3.0,2.0,0.35,Norwich,Connecticut,6360.0,1144.0,NaT,225000.0,"Norwich,Connecticut"
777942,for_sale,2.0,1.0,NaN,Forest Hills,New York,11375.0,NaN,NaT,525000.0,"Forest Hills,New York"
775749,for_sale,1.0,1.0,NaN,Flushing,New York,11370.0,NaN,2004-07-19,425000.0,"Flushing,New York"

In [ ]:
for city, data in grp:
  print(city)
  print(data.shape[0])

Abbot,Maine
15
Aberdeen,New Jersey
201
Abington,Massachusetts
166
Abington,Pennsylvania
13
Absecon Highlands,New Jersey
4
Absecon,New Jersey
353
Accord,New York
5
Acton,Maine
53
Acton,Massachusetts
798
Acushnet,Massachusetts
97
Acworth,New Hampshire
131
Adams,Massachusetts
870
Adamstown Township,Maine
7
Addisleigh Park,New York
27
Addison,Maine
93
Addison,Vermont
32
Adelphia,New Jersey
3
Adjuntas,Puerto Rico
33
Agawam,Massachusetts
872
Aguada,Puerto Rico
261
Aguadilla,Puerto Rico
188
Aguas Buenas,Puerto Rico
82
Aibonito,Puerto Rico
102
Airmont,New York
30
Albany,New Hampshire
28
Albany,Vermont
43
Albertson,New York
5
Albion,Maine
4
Alburgh,Vermont
75
Aldan,Pennsylvania
43
Alexander,Maine
28
Alexandria Township,New Jersey
27
Alexandria,New Hampshire
109
Alford,Massachusetts
77
Alfred,Maine
13
Allagash,Maine
1
Allamuchy Township,New Jersey
160
Allendale,New Jersey
128
Allenhurst,New Jersey
22
Allenstown,New Hampshire
96
Allentown,New Jersey
184
Allenwood,New Jersey
21
Alloway,New Jersey
66
Allston,Massachusetts
30
Alna,Maine
1
Alpha,New Jersey
19
Alpine,New Jersey
199
Alstead,New Hampshire
235
Alton,Maine
12
Alton,New Hampshire
539
Amawalk,New York
2
Ambler,Pennsylvania
5
Amenia,New York
73
Amesbury,Massachusetts
484
Amherst,Maine
32
Amherst,Massachusetts
685
Amherst,New Hampshire
395
Amity,Maine
10
Anasco,Puerto Rico
53
Ancram,New York
56
Ancramdale,New York
6
Andover,Connecticut
91
Andover,Maine
7
Andover,Massachusetts
629
Andover,New Hampshire
173
Andover,New Jersey
209
Andover,Vermont
108
Annandale,New Jersey
2
Anson,Maine
80
Ansonia,Connecticut
233
Antrim,New Hampshire
228
Appleton,Maine
120
Aquinnah,Massachusetts
7
Arden,New York
6
Ardmore,Pennsylvania
56
Ardsley,New York
35
Arecibo,Puerto Rico
481
Argyle Township,Maine
9
Argyle,New York
103
Arlington,Massachusetts
1097
Arlington,Vermont
137
Armonk,New York
34
Arrowsic,Maine
1
Arroyo,Puerto Rico
57
Arundel,Maine
53
Arverne,New York
63
Asbury Park,New Jersey
432
Ashburnham,Massachusetts
201
Ashby,Massachusetts
152
Ashfield,Massachusetts
64
Ashford,Connecticut
187
Ashland,Maine
16
Ashland,Massachusetts
236
Ashland,New Hampshire
121
Aston,Pennsylvania
72
Astoria,New York
1006
Atco,New Jersey
294
Athens,Maine
13
Athens,Vermont
19
Athol,Massachusetts
465
Atkinson,Maine
11
Atkinson,New Hampshire
276
Atlantic City,New Jersey
1400
Atlantic Highlands,New Jersey
115
Atlantique,New York
2
Attleboro,Massachusetts
593
Auburn,Maine
353
Auburn,Massachusetts
516
Auburn,New Hampshire
71
Audubon,New Jersey
73
Augusta,Maine
607
Ausable,New York
5
Austerlitz,New York
184
Avalon Manor,New Jersey
22
Avalon,New Jersey
310
Avenel,New Jersey
285
Averill,Vermont
7
Avon By The Sea,New Jersey
41
Avon,Connecticut
1267
Avon,Maine
8
Avon,Massachusetts
54
Avondale,Pennsylvania
8
Ayer,Massachusetts
288
Back Bay,Massachusetts
86
Baileyville,Maine
24
Bakersfield,Vermont
14
Bala Cynwyd,Pennsylvania
27
Baldwin,Maine
32
Baldwin,New York
1
Baltimore,Vermont
44
Bangor,Maine
642
Bangor,Pennsylvania
33
Bar Harbor,Maine
183
Barceloneta,Puerto Rico
65
Bardonia,New York
22
Baring Plt,Maine
6
Barkhamsted,Connecticut
274
Barnard,Vermont
150
Barnegat Light,New Jersey
14
Barnegat Township,New Jersey
14
Barnegat,New Jersey
492
Barnet,Vermont
205
Barnstable,Massachusetts
403
Barnstead,New Hampshire
322
Barranquitas,Puerto Rico
47
Barre,Massachusetts
249
Barre,Vermont
1248
Barrington,New Hampshire
291
Barrington,New Jersey
34
Barrington,Rhode Island
588
Barryville,New York
7
Bartlett,New Hampshire
340
Barton,Vermont
258
Basking Ridge,New Jersey
16
Bass River,New Jersey
5
Bath Beach,New York
10
Bath,Maine
328
Bath,New Hampshire
153
Bay Head,New Jersey
36
Bayamon,Puerto Rico
1927
Bayamón,Puerto Rico
67
Bayonne,New Jersey
1003
Bayside,New York
1933
Bayville,New Jersey
335
Beach Haven West,New Jersey
31
Beach Haven,New Jersey
74
Beachwood,New Jersey
133
Beacon Falls,Connecticut
97
Beals,Maine
28
Bear,Delaware
64
Beaver Cove,Maine
6
Becket,Massachusetts
985
Bed Stuy,New York
241
Beddington,Maine
8
Bedford,Massachusetts
313
Bedford,New Hampshire
523
Bedford,New York
2
Bedminster Twp,New Jersey
360
Bedstuy Brooklyn,New York
34
Beechhurst,New York
189
Beekmantown,New York
3
Beesleys Point,New Jersey
18
Belchertown,Massachusetts
1441
Belfast,Maine
144
Belford,New Jersey
59
Belgrade,Maine
148
Belle Harbor,New York
12
Belle Mead,New Jersey
91
Belle Terre,New York
5
Belleplain,New Jersey
10
Bellerose village,New York
10
Bellerose,New York
311
Belleville,New Jersey
1500
Bellingham,Massachusetts
198
Bellmawr,New Jersey
91
Belmar,New Jersey
130
Belmont,Maine
29
Belmont,Massachusetts
797
Belmont,New Hampshire
153
Belvidere,New Jersey
31
Belvidere,Vermont
75
Benedicta,Maine
11
Bennington,New Hampshire
97
Bennington,Vermont
397
Bensalem,Pennsylvania
74
Benson,Vermont
64
Benton,Maine
26
Benton,New Hampshire
38
Bergenfield,New Jersey
442
Berkeley Heights Twp,New Jersey
352
Berkeley Heights,New Jersey
8
Berkeley Township,New Jersey
2
Berkeley,New Jersey
50
Berkley,Massachusetts
126
Berkshire,Vermont
67
Berlin,Connecticut
571
Berlin,Massachusetts
166
Berlin,New Hampshire
421
Berlin,New Jersey
234
Berlin,New York
37
Berlin,Vermont
133
Bernards Twp,New Jersey
1053
Bernardston,Massachusetts
316
Bernardsville,New Jersey
469
Berwick,Maine
89
Berwyn,Pennsylvania
36
Bethany,Connecticut
99
Bethel,Connecticut
155
Bethel,Maine
162
Bethel,New York
10
Bethel,Vermont
115
Bethlehem Township,New Jersey
24
Bethlehem,Connecticut
135
Bethlehem,New Hampshire
144
Beverly,Massachusetts
321
Beverly,New Jersey
49
Biddeford,Maine
237
Big Lake Township,Maine
1
Big Moose Township,Maine
1
Billerica,Massachusetts
653
Bingham,Maine
36
Black Brook,New York
1
Blackstone,Massachusetts
180
Blackwood,New Jersey
339
Blaine,Maine
16
Blairstown,New Jersey
113
Blanchard Township,Maine
8
Blandford,Massachusetts
216
Blauvelt,New York
12
Block Island,Rhode Island
45
Bloomfield,Connecticut
741
Bloomfield,New Jersey
1924
Bloomfield,Vermont
12
Blooming Grove,New York
6
Bloomingdale,New Jersey
166
Bloomsbury,New Jersey
10
Blue Anchor,New Jersey
3
Blue Hill,Maine
138
Bogota,New Jersey
297
Bolton,Connecticut
117
Bolton,Massachusetts
355
Bolton,Vermont
27
Boonton Township,New Jersey
187
Boonton,New Jersey
194
Boothbay Harbor,Maine
132
Boothbay,Maine
196
Boothwyn,Pennsylvania
40
Boqueron,Puerto Rico
1
Bordentown,New Jersey
299
Boscawen,New Hampshire
71
Boston,Massachusetts
31502
Bound Brook,New Jersey
372
Bourne,Massachusetts
321
Bournedale,Massachusetts
10
Bow,New Hampshire
79
Bowdoin,Maine
14
Bowdoinham,Maine
80
Bowerbank,Maine
12
Boxborough,Massachusetts
694
Boxford,Massachusetts
164
Boylston,Massachusetts
198
Bozrah,Connecticut
99
Bradford,Maine
4
Bradford,New Hampshire
122
Bradford,Vermont
234
Bradley Beach,New Jersey
82
Bradley,Maine
28
Braintree,Massachusetts
350
Braintree,Vermont
25
Branchburg Township,New Jersey
356
Branchburg,New Jersey
33
Branchville,New Jersey
25
Brandon,Vermont
310
Branford,Connecticut
505
Brattleboro,Vermont
785
Breezy Point,New York
8
Bremen,Maine
2
Brentwood,New Hampshire
455
Brewer,Maine
199
Brewster,Massachusetts
219
Brewster,New York
83
Briarcliff Manor,New York
22
Briarwood,New York
509
Brick Township,New Jersey
15
Brick,New Jersey
1706
Bridgeport,Connecticut
1240
Bridgeport,New Jersey
4
Bridgeton,New Jersey
1028
Bridgewater Twp,New Jersey
922
Bridgewater,Connecticut
83
Bridgewater,Massachusetts
222
Bridgewater,New Hampshire
64
Bridgewater,New Jersey
34
Bridgewater,Vermont
243
Bridgton,Maine
218
Bridport,Vermont
43
Brielle,New Jersey
123
Brigantine City,New Jersey
3
Brigantine,New Jersey
381
Brighton Beach,New York
1
Brighton,Massachusetts
92
Brighton,Vermont
162
Brimfield,Massachusetts
215
Bristol,Connecticut
2115
Bristol,Maine
217
Bristol,New Hampshire
216
Bristol,Pennsylvania
110
Bristol,Rhode Island
417
Bristol,Vermont
142
Broad Channel,New York
78
Brockton,Massachusetts
1189
Bronx,New York
10101
Bronxville,New York
446
Brookfield,Connecticut
160
Brookfield,Massachusetts
204
Brookfield,New Hampshire
35
Brookfield,Vermont
100
Brookhaven,Pennsylvania
102
Brooklawn,New Jersey
36
Brooklin,Maine
105
Brookline,Massachusetts
2561
Brookline,New Hampshire
102
Brookline,Vermont
22
Brooklyn Heights,New York
4
Brooklyn,Connecticut
480
Brooklyn,New York
22210
Brooks,Maine
31
Brooksville,Maine
81
Brookton,Maine
6
Brookville,New York
1
Broomall,Pennsylvania
80
Brownfield,Maine
47
Brownington,Vermont
76
Browns Mills,New Jersey
852
Brownville,Maine
20
Brownville,New York
212
Brunswick,Maine
407
Brunswick,New York
5
Bryn Mawr,Pennsylvania
77
Buckfield,Maine
20
Buckland,Massachusetts
205
Bucksport,Maine
176
Budd Lake,New Jersey
5
Buena Vista Township,New Jersey
36
Buena Vista,New Jersey
2
Buena,New Jersey
91
Burke,Vermont
303
Burleigh,New Jersey
4
Burlington City,New Jersey
4
Burlington Township,New Jersey
36
Burlington,Connecticut
626
Burlington,Maine
4
Burlington,Massachusetts
412
Burlington,New Jersey
766
Burlington,Vermont
301
Burnham,Maine
4
Burrillville,Rhode Island
489
Bushkill,Pennsylvania
342
Butler,New Jersey
165
Buxton,Maine
73
Buzzards Bay,Massachusetts
110
Byram Township,New Jersey
285
Byron,Maine
1
Cabo Rojo,Puerto Rico
380
Cabot,Vermont
148
Cadyville,New York
1
Caguas,Puerto Rico
759
Calais,Maine
75
Calais,Vermont
117
Caldwell Boro Township,New Jersey
154
Caldwell,New Jersey
76
Califon,New Jersey
60
Cambria Heights,New York
165
Cambridge Village,New York
6
Cambridge,Maine
1
Cambridge,Massachusetts
2786
Cambridge,New Hampshire
3
Cambridge,New York
122
Cambridge,Vermont
429
Camden,Maine
103
Camden,New Jersey
313
Campton,New Hampshire
523
Camuy,Puerto Rico
143
Canaan,Connecticut
105
Canaan,Maine
82
Canaan,New Hampshire
404
Canaan,New York
212
Canaan,Vermont
51
Canarsie,New York
32
Candia,New Hampshire
15
Canovanas,Puerto Rico
288
Canterbury,Connecticut
450
Canterbury,New Hampshire
31
Canton,Connecticut
591
Canton,Maine
18
Canton,Massachusetts
636
Cape Charles,Virginia
11
Cape Elizabeth,Maine
64
Cape May Beach,New Jersey
19
Cape May Court House,New Jersey
645
Cape May Point,New Jersey
22
Cape May,New Jersey
184
Caratunk,Maine
6
Caribou,Maine
306
Carlisle,Massachusetts
69
Carlstadt,New Jersey
118
Carmel Hamlet,New York
1
Carmel,Maine
1
Carmel,New York
43
Carneys Point,New Jersey
86
Caroga,New York
3
Carolina,Puerto Rico
1421
Carrabassett Valley,Maine
96
Carroll Plt,Maine
3
Carroll,New Hampshire
67
Carrying Place Town Township,Maine
3
Carteret,New Jersey
495
Carthage,Maine
20
Carver,Massachusetts
148
Carversville,Pennsylvania
1
Cary Plt,Maine
6
Casco,Maine
438
Castine,Maine
80
Castle Hill,Maine
29
Castleton,Vermont
616
Caswell,Maine
9
Catano,Puerto Rico
162
Cataumet,Massachusetts
38
Cathance Township,Maine
14
Cavendish,Vermont
361
Cayey,Puerto Rico
340
Cedar Grove,New Jersey
308
Cedarhurst,New York
6
Cedarville,New Jersey
111
Ceiba,Puerto Rico
37
Centereach,New York
55
Centerville,Massachusetts
336
Central Falls,Rhode Island
178
Central Valley,New York
3
Chadds Ford,Pennsylvania
50
Champlain,New York
32
Chaplin,Connecticut
139
Chapman,Maine
28
Chappaqua,New York
3
Charlemont,Massachusetts
81
Charleston,Maine
35
Charleston,Vermont
74
Charlestown,Massachusetts
194
Charlestown,New Hampshire
306
Charlestown,Rhode Island
251
Charlotte,Vermont
64
Charlton,Massachusetts
378
Chatham Township,New Jersey
430
Chatham Village,New York
3
Chatham,Massachusetts
341
Chatham,New Hampshire
11
Chatham,New Jersey
297
Chatham,New York
121
Chatsworth,New Jersey
14
Chazy,New York
11
Chebeague Island,Maine
4
Chelmsford,Massachusetts
646
Chelsea,Maine
22
Chelsea,Massachusetts
698
Chelsea,Vermont
84
Cheltenham,Pennsylvania
26
Cherry Hill Township,New Jersey
2
Cherry Hill,New Jersey
380
Cherryfield,Maine
52
Cheshire,Connecticut
548
Cheshire,Massachusetts
352
Chesilhurst,New Jersey
17
Chester Heights,Pennsylvania
1
Chester Township,New Jersey
332
Chester Twp,New Jersey
30
Chester,Connecticut
105
Chester,Maine
3
Chester,Massachusetts
273
Chester,New Hampshire
88
Chester,New Jersey
81
Chester,New York
23
Chester,Pennsylvania
178
Chester,Vermont
644
Chesterfield,Massachusetts
34
Chesterfield,New Hampshire
655
Chesterfield,New Jersey
116
Chesterfield,New York
12
Chesterville,Maine
38
Chestnut Ridge,New York
15
Cheyney,Pennsylvania
2
Chichester,New Hampshire
80
Chicopee,Massachusetts
1292
Chilmark,Massachusetts
15
China,Maine
248
Chincoteague,Virginia
20
Chittenden,Vermont
31
Christiansted,Virgin Islands
1287
Ciales,Puerto Rico
125
Cidra,Puerto Rico
346
Cinnaminson,New Jersey
120
City of Orange Township,New Jersey
773
Claremont,New Hampshire
671
Clarendon,Vermont
220
Clark,New Jersey
233
Clarksboro,New Jersey
60
Clarksburg,Massachusetts
255
Clarksburg,New Jersey
10
Clarksville,New Hampshire
14
Claverack,New York
79
Claymont,Delaware
94
Clayton,New Jersey
204
Clementon,New Jersey
146
Clermont,New Jersey
26
Cliffside Park,New Jersey
1294
Cliffwood Beach,New Jersey
25
Cliffwood,New Jersey
35
Clifton Heights,Pennsylvania
90
Clifton,Maine
11
Clifton,New Jersey
2700
Clinton Corners,New York
37
Clinton Township,New Jersey
163
Clinton,Connecticut
179
Clinton,Maine
64
Clinton,Massachusetts
167
Clinton,New Jersey
24
Clintonville,New York
8
Closter,New Jersey
186
Coamo,Puerto Rico
103
Cody,Wyoming
3
Cohasset,Massachusetts
173
Colchester,Connecticut
457
Colchester,Vermont
169
Cold Spring,New Jersey
6
Colebrook,Connecticut
96
Colebrook,New Hampshire
152
College Point,New York
752
Collingdale,Pennsylvania
33
Collingswood,New Jersey
68
Colonia,New Jersey
276
Colrain,Massachusetts
105
Colts Neck,New Jersey
232
Columbia Falls,Maine
36
Columbia,Connecticut
372
Columbia,Maine
9
Columbia,New Hampshire
24
Columbia,New Jersey
2
Columbus,New Jersey
302
Comerio,Puerto Rico
85
Concord Township,Maine
12
Concord,Massachusetts
576
Concord,New Hampshire
500
Concord,Vermont
155
Condado,Puerto Rico
1
Congers,New York
18
Connor Township,Maine
1
Conshohocken,Pennsylvania
53
Conway,Massachusetts
108
Conway,New Hampshire
845
Cookstown,New Jersey
33
Cooper,Maine
2
Copake Falls,New York
17
Copake,New York
169
Coplin Plt,Maine
7
Coram,New York
80
Corbin City,New Jersey
24
Corinna,Maine
20
Corinth,Maine
28
Corinth,Vermont
111
Cornish,Maine
18
Cornish,New Hampshire
134
Cornville,Maine
65
Cornwall,Connecticut
117
Cornwall,Vermont
32
Corona,New York
1087
Corozal,Puerto Rico
194
Cortlandt Manor,New York
1
Cos Cob,Connecticut
35
Cotuit,Massachusetts
116
Coventry,Connecticut
632
Coventry,Rhode Island
1052
Coventry,Vermont
53
Craftsbury,Vermont
137
Cranberry Isles,Maine
58
Cranbury,New Jersey
168
Cranford,New Jersey
419
Cranston,Rhode Island
1833
Craryville,New York
30
Crawford,Maine
8
Cream Ridge,New Jersey
153
Cresskill,New Jersey
404
Cromwell,Connecticut
662
Cross Lake Township,Maine
10
Crosswicks,New Jersey
12
Croton On Hudson,New York
9
Crown Heights,New York
297
Crown Point,New York
140
Croydon,New Hampshire
105
Croydon,Pennsylvania
19
Crum Lynne,Pennsylvania
23
Crystal,Maine
8
Cuddebackville,New York
1
Culebra,Puerto Rico
13
Cumberland,Maine
86
Cumberland,Rhode Island
1501
Cummaquid,Massachusetts
14
Cummington,Massachusetts
67
Cushing,Maine
126
Cutler,Maine
26
Dallas Plt,Maine
69
Dalton,Massachusetts
230
Dalton,New Hampshire
91
Damariscotta,Maine
59
Danbury,Connecticut
424
Danbury,New Hampshire
125
Danby,Vermont
278
Danforth,Maine
29
Danvers,Massachusetts
285
Danville,New Hampshire
144
Danville,Vermont
264
Darby,Pennsylvania
170
Darien,Connecticut
159
Dartmouth,Massachusetts
306
Dayton,Maine
46
Dayton,New Jersey
22
Deal,New Jersey
33
Dedham,Maine
61
Dedham,Massachusetts
593
Deep River,Connecticut
177
Deepwater,New Jersey
21
Deer Isle,Maine
143
Deerfield,Massachusetts
176
Deerfield,New Hampshire
213
Deering,New Hampshire
49
Del Haven,New Jersey
49
Delanco,New Jersey
87
Delaware City,Delaware
35
Delaware Township,Pennsylvania
2
Delaware Water Gap,Pennsylvania
4
Delaware,New Jersey
57
Delmont,New Jersey
25
Delran,New Jersey
148
Demarest,New Jersey
193
Denmark,Maine
29
Dennis Port,Massachusetts
169
Dennis Township,New Jersey
9
Dennis,Massachusetts
292
Dennisville,New Jersey
18
Dennysville,Maine
15
Denville,New Jersey
615
Deptford Township,New Jersey
6
Deptford,New Jersey
76
Derby,Connecticut
212
Derby,Vermont
382
Derry,New Hampshire
502
Detroit,Maine
25
Devens,Massachusetts
172
Devon,Pennsylvania
7
Devonshire,New Jersey
30
Dexter,Maine
219
Diamond Beach,New Jersey
3
Dighton,Massachusetts
126
Dingmans Ferry,Pennsylvania
237
Dixfield,Maine
156
Dixmont,Maine
37
Dobbs Ferry,New York
62
Dorado,Puerto Rico
838
Dorchester,Massachusetts
54
Dorchester,New Hampshire
85
Dorchester,New Jersey
22
Dorothy,New Jersey
41
Dorset,Vermont
347
Douglas,Massachusetts
298
Douglaston,New York
311
Dover Foxcroft,Maine
100
Dover Plains,New York
74
Dover,Delaware
11
Dover,Massachusetts
178
Dover,New Hampshire
473
Dover,New Jersey
212
Dover,New York
8
Dover,Vermont
1569
Doylestown,Pennsylvania
7
Dracut,Massachusetts
512
Dresden,Maine
44
Dresden,New York
55
Dresher,Pennsylvania
10
Drexel Hill,Pennsylvania
221
Dublin,New Hampshire
54
Dudley,Massachusetts
375
Dummer,New Hampshire
30
Dummerston,Vermont
26
Dumont,New Jersey
321
Dunbarton,New Hampshire
92
Dunellen Borough,New Jersey
21
Dunellen,New Jersey
318
Dunstable,Massachusetts
75
Durham,Connecticut
136
Durham,Maine
70
Durham,New Hampshire
257
Duxbury,Massachusetts
93
Duxbury,Vermont
61
Dyer Brook,Maine
8
Dyker Heights,New York
7
Eagle Lake,Maine
47
Eagleswood Township,New Jersey
11
Eagleville,Pennsylvania
2
East Amwell Township,New Jersey
74
East Amwell,New Jersey
13
East Bangor,Pennsylvania
3
East Boston,Massachusetts
128
East Bridgewater,Massachusetts
151
East Brookfield,Massachusetts
21
East Brunswick,New Jersey
1191
East Chatham,New York
35
East Dennis,Massachusetts
126
East Elmhurst,New York
1130
East Falmouth,Massachusetts
633
East Flatbush,New York
125
East Granby,Connecticut
356
East Greenbush,New York
1
East Greenwich Township,New Jersey
7
East Greenwich,Rhode Island
519
East Haddam,Connecticut
582
East Hampton,Connecticut
588
East Hanover,New Jersey
213
East Hartford,Connecticut
1621
East Harwich,Massachusetts
7
East Haven,Connecticut
382
East Haven,Vermont
27
East Hills,New York
3
East Kingston,New Hampshire
18
East Longmeadow,Massachusetts
373
East Lyme,Connecticut
679
East Machias,Maine
61
East Marion,New York
8
East Millinocket,Maine
27
East Montpelier,Vermont
73
East Moxie Township,Maine
9
East Nassau,New York
27
East New York,New York
3
East Newark,New Jersey
48
East Orange,New Jersey
2605
East Providence,Rhode Island
822
East Rutherford,New Jersey
304
East Sandwich,Massachusetts
174
East Setauket,New York
19
East Stroudsburg,Pennsylvania
172
East Vineland,New Jersey
5
East Wareham,Massachusetts
33
East Windsor,Connecticut
769
East Windsor,New Jersey
472
Eastampton,New Jersey
95
Eastbrook,Maine
15
Eastchester,New York
46
Eastford,Connecticut
162
Eastham,Massachusetts
302
Easthampton,Massachusetts
580
Easton,Connecticut
59
Easton,Maine
35
Easton,Massachusetts
447
Easton,New Hampshire
26
Easton,New York
1
Easton,Pennsylvania
2
Eastport,Maine
97
Eaton,New Hampshire
32
Eatontown,New Jersey
198
Ebeemee Township,Maine
6
Eddington,Maine
56
Eddystone,Pennsylvania
6
Eden,Vermont
260
Edgartown,Massachusetts
72
Edgecomb,Maine
154
Edgewater Park,New Jersey
65
Edgewater,New Jersey
1439
Edinburg,Maine
1
Edison,New Jersey
1576
Edmunds Township,Maine
6
Effingham,New Hampshire
117
Egg Harbor City,New Jersey
370
Egg Harbor Township,New Jersey
1674
Egg Harbor,New Jersey
9
Egremont,Massachusetts
135
Elberon,New Jersey
40
Eldora,New Jersey
28
Eldred,New York
15
Eliot,Maine
158
Elizabeth City,New Jersey
1346
Elizabeth,New Jersey
234
Elizabethtown,New York
15
Elizaville,New York
6
Elk Township,New Jersey
4
Elkins Park,Pennsylvania
113
Ellington,Connecticut
747
Elliottsville Township,Maine
2
Ellsworth,Maine
131
Elmer,New Jersey
347
Elmhurst,New York
969
Elmont,New York
170
Elmore,Vermont
147
Elmsford,New York
33
Elmwood Park,New Jersey
689
Elsmere,Delaware
2
Embden,Maine
64
Emerson,New Jersey
117
Enfield,Connecticut
1868
Enfield,Maine
39
Enfield,New Hampshire
284
Englewood Cliffs,New Jersey
277
Englewood,New Jersey
792
Englishtown,New Jersey
112
Enosburg Falls,Vermont
131
Epping,New Hampshire
634

In [ ]:
## Que ciudades tienen las casas caras y baratas

median_price_city = grp["price"].median()

median_price_city

                        city_state     price
0                      Abbot,Maine   39900.0
1              Aberdeen,New Jersey  499900.0
2           Abington,Massachusetts  525000.0
3            Abington,Pennsylvania  320000.0
4     Absecon Highlands,New Jersey   89000.0
...                            ...       ...
3056             Yauco,Puerto Rico   70500.0
3057           Yeadon,Pennsylvania  215000.0
3058              Yonkers,New York  299900.0
3059                    York,Maine  619000.0
3060                Yulan,New York  188500.0

[3061 rows x 2 columns]

In [ ]:
min_max_city = grp["price"].agg(["median", "mean", "max", "min", "std", "count"])
min_max_city

,city_state,median,mean,max,min,std,count
0,"Abbot,Maine",39900.0,200013.333333,425000.0,21900.0,1.922600e+05,15
1,"Aberdeen,New Jersey",499900.0,452762.691542,849900.0,49000.0,1.613619e+05,201
2,"Abington,Massachusetts",525000.0,821046.385542,7900000.0,250000.0,1.498363e+06,166
3,"Abington,Pennsylvania",320000.0,306587.692308,399440.0,229000.0,5.231031e+04,13
4,"Absecon Highlands,New Jersey",89000.0,89000.000000,89000.0,89000.0,0.000000e+00,4
...,...,...,...,...,...,...,...
3056,"Yauco,Puerto Rico",70500.0,151775.925926,4000000.0,32500.0,3.914199e+05,108
3057,"Yeadon,Pennsylvania",215000.0,208861.538462,280000.0,25000.0,7.927538e+04,13
3058,"Yonkers,New York",299900.0,421251.046487,2199000.0,44900.0,3.096938e+05,1893
3059,"York,Maine",619000.0,929687.190698,5950000.0,21000.0,1.222300e+06,430
3060,"Yulan,New York",188500.0,254166.666667,425000.0,149000.0,1.335008e+05,6

In [ ]:
min_max_city.sort_values("median", ascending=False, inplace=True)
min_max_city

,city_state,median,mean,max,min,std,count
2821,"Waterfront,Massachusetts",12000000.0,1.200000e+07,12000000.0,12000000.0,0.000000e+00,25
2243,"Rochdale Village,New York",9800000.0,9.800000e+06,9800000.0,9800000.0,0.000000e+00,3
1628,"Middletown Township,New Jersey",9199999.5,9.200000e+06,17500000.0,899999.0,9.092195e+06,6
2424,"Siasconset,Massachusetts",6495000.0,6.495000e+06,6495000.0,6495000.0,0.000000e+00,3
2650,"Tisbury,Massachusetts",5750000.0,6.406333e+06,11600000.0,699000.0,4.828756e+06,15
...,...,...,...,...,...,...,...
1930,"Oakfield,Maine",14000.0,1.931667e+04,30000.0,14000.0,7.853295e+03,12
1969,"Orient,Maine",12500.0,1.250000e+04,12500.0,12500.0,NaN,1
1398,"Lehman,Pennsylvania",12500.0,1.310909e+04,17500.0,9900.0,2.700909e+03,11
1377,"Laureldale,New Jersey",9900.0,3.066923e+04,279900.0,9900.0,7.488453e+04,13
2130,"Port Murray,New Jersey",8000.0,9.700000e+03,15000.0,8000.0,2.790858e+03,10

In [ ]:
## veamos ahora cantidad de valores por estados
realtor_data["state"].value_counts()

state
New Jersey        231958
New York          197215
Massachusetts     175248
Connecticut        89778
New Hampshire      51394
Vermont            46460
Maine              36650
Rhode Island       29596
Puerto Rico        24679
Pennsylvania       17148
Virgin Islands      2573
Delaware            2135
Georgia               50
Virginia              31
South Carolina        25
Tennessee             20
Wyoming                3
West Virginia          3
Name: count, dtype: int64

In [ ]:
## Utilicemos consultas anidadas o varias al tiempo
home_sizes_by_city= (grp["house_size"]
    .agg(["median", "mean", "max", "min", "std"])
    .sort_values("median", ascending=False)
)
home_sizes_by_city
### En la interpretación las primeras corresponden a las casas más grandes.

,city_state,median,mean,max,min,std
2634,"Tenafly,New Jersey",47916.0,47916.000000,47916.0,47916.0,0.000000
962,"Garfield,New Jersey",19998.0,11885.848485,19998.0,1556.0,8959.957859
609,"Cresskill,New Jersey",19110.0,19110.000000,19110.0,19110.0,0.000000
1879,"North Haledon,New Jersey",17250.0,15794.666667,17250.0,4152.0,4366.000000
2243,"Rochdale Village,New York",15000.0,15000.000000,15000.0,15000.0,0.000000
...,...,...,...,...,...,...
2962,"Williamsburg,New York",NaN,NaN,NaN,NaN,NaN
2991,"Windsor,New Hampshire",NaN,NaN,NaN,NaN,NaN
2997,"Winslow Township,New Jersey",NaN,NaN,NaN,NaN,NaN
3020,"Woodcliff Lake,New Jersey",NaN,NaN,NaN,NaN,NaN
3046,"Wyman Township,Maine",NaN,NaN,NaN,NaN,NaN

In [ ]:
## Ahora respondamos a la pregunta ¿Qué combianción de dormitorios y baños son los más comunes en data frame ?, ej 1 habitacion y 2 baños
realtor_data.groupby(["bed", "bath"], as_index=False)["city"].count() ## realiza el conteo por ciudad

In [ ]:
## Ahora la consulta anterior no responde lo que necesitamos
counts = realtor_data.groupby(["bed", "bath"], as_index=False)["city"].count().rename({"city":"count"}, axis = 1)

In [ ]:
counts.sort_values("count", ascending=False)

## si es nuestro interes organizar los index dados que están desordenados (reset_index)
counts = counts.sort_values("count", ascending=False).reset_index(drop=True)
counts

       bed   bath   count
0      3.0    2.0  114283
1      2.0    2.0   88319
2      1.0    1.0   71933
3      3.0    3.0   69601
4      2.0    1.0   57583
..     ...    ...     ...
258   36.0   12.0       1
259   33.0   35.0       1
260   18.0   18.0       1
261    1.0    6.0       1
262  123.0  123.0       1

[263 rows x 3 columns]

In [ ]:
## Como reorganizamos el codigo anterior
counts = (
    realtor_data.groupby(["bed", "bath"], as_index=False)["city"]
    .count()
    .rename({"city":"count"}, axis = 1)
    .sort_values("count", ascending=False)  ## si es nuestro interes organizar los index dados que están desordenados (reset_index)
    .reset_index(drop=True)
)

counts

       bed   bath   count
0      3.0    2.0  114283
1      2.0    2.0   88319
2      1.0    1.0   71933
3      3.0    3.0   69601
4      2.0    1.0   57583
..     ...    ...     ...
258   36.0   12.0       1
259   33.0   35.0       1
260   18.0   18.0       1
261    1.0    6.0       1
262  123.0  123.0       1

[263 rows x 3 columns]

# Volvamos al marco de datos de restarantes

In [ ]:
restaurants.sample(3)

,Yelp URL,Name,Street Address,Zip Code,City,State,Price Range,Phone,Rating,Number of Reviews,Website,Menu Link,Image 1,Image 2,Image 3,Category 1,Category 2,Category 3
682,https://www.yelp.com/biz/egypt-smoke-rowland-h...,Egypt Smoke,18253 Colima Rd Ste 203,91748.0,Rowland Heights,CA,$$,(626) 460-0650,4.5,169.0,NaN,NaN,https://s3-media0.fl.yelpcdn.com/bphoto/5xAq3V...,https://s3-media0.fl.yelpcdn.com/bphoto/cZAI9j...,https://s3-media0.fl.yelpcdn.com/bphoto/fofITD...,Lounges,Hookah Bars,NaN
971,https://www.yelp.com/biz/lau-bo-by-lao-beo-gar...,Lau Bo by Lao Beo,14271 Brookhurst St,92843.0,Garden Grove,CA,NaN,(714) 617-4229,4.0,7.0,NaN,NaN,https://s3-media0.fl.yelpcdn.com/bphoto/jl3v2P...,https://s3-media0.fl.yelpcdn.com/bphoto/5NE1iw...,https://s3-media0.fl.yelpcdn.com/bphoto/0hY36_...,Vietnamese,NaN,NaN
648,https://www.yelp.com/biz/corazon-taste-of-mexi...,Corazon Taste of Mexico,120 S Brea Blvd Ste 106,92821.0,Brea,CA,$$,(657) 286-7922,4.5,931.0,www.corazontm.com,www.corazontm.com/menus/,https://s3-media0.fl.yelpcdn.com/bphoto/lBY-AC...,https://s3-media0.fl.yelpcdn.com/bphoto/m-Taai...,https://s3-media0.fl.yelpcdn.com/bphoto/L36mb-...,Mexican,Wine Bars,Seafood

In [ ]:
ratings_by_city = restaurants.groupby("City")["Rating"].agg(["mean", "median", "count", "std"]).sort_values("mean", ascending=False)
ratings_by_city
## los primeros son errores dado que son ciudades

                            mean  median  count       std
City
Baldwin Park            5.000000    5.00      1       NaN
Stanton                 4.666667    5.00      9  0.661438
Tustin                  4.500000    4.50      1       NaN
Norwalk                 4.500000    4.50      2  0.000000
La Puente               4.500000    4.50      6  0.316228
Corona                  4.500000    4.50      1       NaN
La Verne                4.500000    4.50      2  0.000000
City of Industry        4.500000    4.50      1       NaN
Westminster             4.500000    4.50      4  0.000000
Chino                   4.500000    4.50     24  0.361158
Ontario                 4.500000    4.50     11  0.316228
Villa Park              4.500000    4.50      2  0.000000
Upland                  4.500000    4.50      6  0.316228
Walnut                  4.481481    4.50     27  0.448962
Garden Grove            4.428571    4.50     35  0.422577
Pomona                  4.413793    4.50     29  0.464238
La Mirada               4.394737    4.50     19  0.657836
Buena Park              4.375000    4.50     44  0.375484
West Covina             4.333333    4.50     39  0.331133
La Habra                4.333333    4.50     33  0.645497
Cypress                 4.333333    4.25      6  0.408248
Whittier                4.314286    4.50     35  0.299158
Diamond Bar             4.304054    4.50     74  0.502170
Placentia               4.303571    4.50     28  0.458243
Anaheim                 4.302013    4.50    149  0.550856
El Monte                4.300000    4.50      5  0.447214
Cerritos                4.300000    4.50      5  0.273861
Fullerton               4.262987    4.50    154  0.413016
Anaheim Hills           4.250000    4.50      8  0.462910
La Palma                4.250000    4.50      6  0.612372
City Of Industry        4.250000    4.25      2  0.353553
Covina                  4.238095    4.00     21  0.538958
City of Industry        4.229167    4.50     24  0.441814
Orange                  4.205882    4.50     68  0.490471
Claremont               4.204545    4.25     22  0.427035
Rowland Heights         4.180556    4.00     72  0.368720
Hacienda Heights        4.176471    4.00     17  0.350944
Yorba Linda             4.111111    4.00     63  0.461803
Brea                    4.078431    4.00    153  0.599116
Chino Hills             4.034091    4.00     44  0.379684
Santa Ana               4.000000    4.00      1       NaN
500 N Harbor Blvd       4.000000    4.00      2  0.000000
Montclair               3.500000    3.50      3  0.500000
5091 Mountain View Ave  3.500000    3.50      2  0.000000

In [ ]:
## Consideremos las ciudad que contenga al menos diez restaurante

ratings_by_city.loc[ratings_by_city["count"] >= 10]

                      mean  median  count       std
City
Chino             4.500000    4.50     24  0.361158
Ontario           4.500000    4.50     11  0.316228
Walnut            4.481481    4.50     27  0.448962
Garden Grove      4.428571    4.50     35  0.422577
Pomona            4.413793    4.50     29  0.464238
La Mirada         4.394737    4.50     19  0.657836
Buena Park        4.375000    4.50     44  0.375484
West Covina       4.333333    4.50     39  0.331133
La Habra          4.333333    4.50     33  0.645497
Whittier          4.314286    4.50     35  0.299158
Diamond Bar       4.304054    4.50     74  0.502170
Placentia         4.303571    4.50     28  0.458243
Anaheim           4.302013    4.50    149  0.550856
Fullerton         4.262987    4.50    154  0.413016
Covina            4.238095    4.00     21  0.538958
City of Industry  4.229167    4.50     24  0.441814
Orange            4.205882    4.50     68  0.490471
Claremont         4.204545    4.25     22  0.427035
Rowland Heights   4.180556    4.00     72  0.368720
Hacienda Heights  4.176471    4.00     17  0.350944
Yorba Linda       4.111111    4.00     63  0.461803
Brea              4.078431    4.00    153  0.599116
Chino Hills       4.034091    4.00     44  0.379684

In [ ]:
## Ahora, dada una combinación de ciudades y rango de precio, ¿donde esta el mejor?

result = restaurants.groupby(["City", "Price Range"])["Rating"].agg(["mean", "median", "count", "std"]).sort_values("mean", ascending=False)

In [ ]:
result[result["count"]>=10]

                                  mean  median  count       std
City             Price Range
Walnut           $$           4.470588    4.50     17  0.483173
Anaheim          $            4.409091    4.50     22  0.590326
La Habra         $$           4.386364    4.50     22  0.554888
Chino            $$           4.361111    4.50     18  0.287257
Fullerton        $            4.354167    4.50     24  0.453948
City of Industry $$           4.318182    4.50     11  0.252262
Placentia        $$           4.309524    4.50     21  0.334522
Buena Park       $$           4.282609    4.50     23  0.331185
Whittier         $$           4.280000    4.50     25  0.291548
Anaheim          $$           4.275000    4.50    100  0.489150
West Covina      $$           4.240741    4.50     27  0.289906
Fullerton        $$           4.239130    4.50    115  0.415425
Garden Grove     $$           4.236842    4.00     19  0.348346
Rowland Heights  $$           4.230769    4.00     52  0.389338
Covina           $$           4.208333    4.50     12  0.620056
Orange           $$           4.202128    4.50     47  0.425538
Yorba Linda      $$           4.170455    4.00     44  0.443862
Diamond Bar      $$           4.147727    4.25     44  0.452121
Brea             $            4.138889    4.00     18  0.659892
Pomona           $$           4.107143    4.00     14  0.289467
Claremont        $$           4.093750    4.00     16  0.417083
Brea             $$           4.089109    4.00    101  0.438155
Orange           $            4.076923    4.00     13  0.571772
Chino Hills      $$           3.951613    4.00     31  0.394859

In [ ]:
restaurants.groupby("Price Range")["Rating"].agg(["mean", "median", "count", "std"]).sort_values("mean", ascending=False)

                 mean  median  count       std
Price Range
$$$$         4.428571     4.5     14  0.181568
$            4.271845     4.5    206  0.502563
$$           4.215591     4.5    821  0.431023
$$$          4.115385     4.0     26  0.637302

### Transfor --- Groupby

* Aprenderemos tranformaciones dentro de grupos

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_parquet("/content/monthly_stocks.parquet") ## conjunto de datos financieros

In [ ]:
data.sample(3)

       symbol                companyName       date  close
198457    LGL        The LGL Group, Inc. 2019-03-31   6.54
279083    PXS         Pyxis Tankers Inc. 2019-11-30   4.64
194026   KYMR  Kymera Therapeutics, Inc. 2022-11-30  28.98

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379719 entries, 0 to 379718
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   symbol       379719 non-null  object
 1   companyName  379719 non-null  object
 2   date         379719 non-null  datetime64[us]
 3   close        379719 non-null  float64
dtypes: datetime64[us](1), float64(1), object(2)
memory usage: 11.6+ MB

In [ ]:
data ## EL conjunto de datos incluye todas las acciones de EEUU que cotizane en el mercado
      # Se evidencia una frecuencia mensual

       symbol                 companyName       date  close
0           A  Agilent Technologies, Inc. 2017-01-31  48.97
1           A  Agilent Technologies, Inc. 2017-02-28  51.30
2           A  Agilent Technologies, Inc. 2017-03-31  52.87
3           A  Agilent Technologies, Inc. 2017-04-30  55.05
4           A  Agilent Technologies, Inc. 2017-05-31  60.34
...       ...                         ...        ...    ...
379714   ZYXI                 Zynex, Inc. 2023-04-30  11.44
379715   ZYXI                 Zynex, Inc. 2023-05-31   9.38
379716   ZYXI                 Zynex, Inc. 2023-06-30   9.59
379717   ZYXI                 Zynex, Inc. 2023-07-31   9.76
379718   ZYXI                 Zynex, Inc. 2023-08-31   7.70

[379719 rows x 4 columns]

In [ ]:
## Escenario donde no quiero juntar sino separar elementos de un campo

data["companyName"].str.split(pat = ',', expand=True) ## si existen espacio utilizamos \s*
####### Como guardar en data frame cada uno de las variables creadas
#data[["Company", "Name"]] = data["companyName"].str.split(pat = ',', n = 1, expand=True)
#data

                           0      1
0       Agilent Technologies   Inc.
1       Agilent Technologies   Inc.
2       Agilent Technologies   Inc.
3       Agilent Technologies   Inc.
4       Agilent Technologies   Inc.
...                      ...    ...
379714                 Zynex   Inc.
379715                 Zynex   Inc.
379716                 Zynex   Inc.
379717                 Zynex   Inc.
379718                 Zynex   Inc.

[379719 rows x 2 columns]

In [ ]:
######  Exploración de datos
## Veamos cuantos simbolos unicos se tienen
data["symbol"].nunique()

5772

In [ ]:
data["close"].mean()

28521.1881465582

In [ ]:
## Debemos ordenar los datos para calcular el cambio porcentual
data = data.sort_values(["symbol", "date"])
data

       symbol                 companyName       date  close
0           A  Agilent Technologies, Inc. 2017-01-31  48.97
1           A  Agilent Technologies, Inc. 2017-02-28  51.30
2           A  Agilent Technologies, Inc. 2017-03-31  52.87
3           A  Agilent Technologies, Inc. 2017-04-30  55.05
4           A  Agilent Technologies, Inc. 2017-05-31  60.34
...       ...                         ...        ...    ...
379714   ZYXI                 Zynex, Inc. 2023-04-30  11.44
379715   ZYXI                 Zynex, Inc. 2023-05-31   9.38
379716   ZYXI                 Zynex, Inc. 2023-06-30   9.59
379717   ZYXI                 Zynex, Inc. 2023-07-31   9.76
379718   ZYXI                 Zynex, Inc. 2023-08-31   7.70

[379719 rows x 4 columns]

In [ ]:
#data.drop(columns=["close_pct_change"], axis = 1)

In [ ]:
## Ahora si la necesidad es calcular el cambio porcentual de una fila respecto a la fila anterior
data["close_pct_change"] = data.groupby("symbol")["close"].pct_change()
data

       symbol                 companyName       date  close  close_pct_change
0           A  Agilent Technologies, Inc. 2017-01-31  48.97               NaN
1           A  Agilent Technologies, Inc. 2017-02-28  51.30          0.047580
2           A  Agilent Technologies, Inc. 2017-03-31  52.87          0.030604
3           A  Agilent Technologies, Inc. 2017-04-30  55.05          0.041233
4           A  Agilent Technologies, Inc. 2017-05-31  60.34          0.096094
...       ...                         ...        ...    ...               ...
379714   ZYXI                 Zynex, Inc. 2023-04-30  11.44         -0.046667
379715   ZYXI                 Zynex, Inc. 2023-05-31   9.38         -0.180070
379716   ZYXI                 Zynex, Inc. 2023-06-30   9.59          0.022388
379717   ZYXI                 Zynex, Inc. 2023-07-31   9.76          0.017727
379718   ZYXI                 Zynex, Inc. 2023-08-31   7.70         -0.211066

[379719 rows x 5 columns]

In [ ]:
## Verifiquemos si el groupby a quedado correcto y para cualquier empresa debe iniciar en NAN

data[data["symbol"] == "AAPL"]
### data = data['symbol'].value_counts()

     symbol companyName       date     close  close_pct_change
1031   AAPL  Apple Inc. 2017-01-31   30.3375               NaN
1032   AAPL  Apple Inc. 2017-02-28   34.2475          0.128883
1033   AAPL  Apple Inc. 2017-03-31   35.9150          0.048690
1034   AAPL  Apple Inc. 2017-04-30   35.9125         -0.000070
1035   AAPL  Apple Inc. 2017-05-31   38.1900          0.063418
...     ...         ...        ...       ...               ...
1106   AAPL  Apple Inc. 2023-04-30  169.6800          0.028987
1107   AAPL  Apple Inc. 2023-05-31  177.2500          0.044613
1108   AAPL  Apple Inc. 2023-06-30  193.9700          0.094330
1109   AAPL  Apple Inc. 2023-07-31  196.4500          0.012785
1110   AAPL  Apple Inc. 2023-08-31  187.8700         -0.043675

[80 rows x 5 columns]

In [ ]:
### Como aplicar transformaciones despues de agrupar

data["close"].transform(["pct_change", "cumsum"]) ## transfor sin agrupar / pct_change = cambio porcentual

        pct_change        cumsum
0              NaN  4.897000e+01
1         0.047580  1.002700e+02
2         0.030604  1.531400e+02
3         0.041233  2.081900e+02
4         0.096094  2.685300e+02
...            ...           ...
379714   -0.046667  1.083004e+10
379715   -0.180070  1.083004e+10
379716    0.022388  1.083004e+10
379717    0.017727  1.083004e+10
379718   -0.211066  1.083004e+10

[379719 rows x 2 columns]

In [ ]:
data.groupby("symbol")["close"].transform("pct_change") ## transfor con agrupar
## obs : Cuando realizas la transform en grupo, no devuelve los simbolos de agrupacion

0              NaN
1         0.047580
2         0.030604
3         0.041233
4         0.096094
            ...
379714   -0.046667
379715   -0.180070
379716    0.022388
379717    0.017727
379718   -0.211066
Name: close, Length: 379719, dtype: float64

In [ ]:
## En el caso del agregado
data.groupby("symbol")["close"].mean()

symbol
A       99.336125
AA      35.955625
AACG     1.562500
AADI    27.406233
AAIC     6.417750
          ...
ZVSA     5.719532
ZWS     30.439000
ZYME    19.956404
ZYNE     6.259161
ZYXI     8.101535
Name: close, Length: 5772, dtype: float64